export type PropertyType = 'Hotels' | 'Resorts' | 'Apartments' | 'Villas';
export type Neighborhood = 'Patong' | 'Karon' | 'Kata' | 'Kamala' | 'Ubud' | 'Seminyak' | 'Nusa Dua' | 'Uluwatu';

export type Hotel = {
  id: string;
  name: string;
  city: string;
  neighborhood: Neighborhood;
  locationLabel: string;
  img: string;
  amenities: string[];
  facilities: string[];
  note: string;
  reviewScore: number;
  reviewLabel: 'Excellent' | 'Exceptional' | 'Great' | 'Good';
  reviews: number;
  price: number;
  was?: number;
  stars: 2 | 3 | 4 | 5;
  type: PropertyType;
  bedTypes: string[];
  topChoice?: boolean;
  address: string;
};

export const MOCK_HOTELS: Hotel[] = [
  {
    id: 'azure-serenity',
    name: 'The Azure Serenity Resort',
    city: 'Bali',
    neighborhood: 'Ubud',
    locationLabel: 'Ubud, Bali • 2.5 km from center',
    img: '/images/search-result/the-azure-serenity-resort.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Breakfast', 'Private Beach', 'Spa', 'Gym'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Fitness Center', 'Spa'],
    note: 'Only 2 rooms left at this price!',
    reviewScore: 8.9,
    reviewLabel: 'Excellent',
    reviews: 1240,
    price: 284,
    was: 320,
    stars: 5,
    type: 'Resorts',
    bedTypes: ['King'],
    topChoice: true,
    address: 'Jl. Raya Sayan, Ubud, Bali',
  },
  {
    id: 'lumina-beach',
    name: 'Lumina Beach Villas',
    city: 'Bali',
    neighborhood: 'Seminyak',
    locationLabel: 'Seminyak, Bali • Beachfront',
    img: '/images/search-result/lumina-beach-villas.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Breakfast', 'Spa', 'Airport Shuttle'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Spa', 'Parking'],
    note: 'Free cancellation before Oct 10',
    reviewScore: 9.2,
    reviewLabel: 'Exceptional',
    reviews: 856,
    price: 415,
    stars: 5,
    type: 'Villas',
    bedTypes: ['King', 'Double'],
    address: 'Jl. Kayu Aya, Seminyak, Bali',
  },
  {
    id: 'palms-sanctuary',
    name: 'The Palms Sanctuary',
    city: 'Bali',
    neighborhood: 'Nusa Dua',
    locationLabel: 'Nusa Dua, Bali • 0.8 km from beach',
    img: '/images/search-result/the-palms-sanctuary.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Breakfast', 'Gym', 'Airport Shuttle'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Fitness Center', 'Parking'],
    note: 'Breakfast + Dinner deal available',
    reviewScore: 8.4,
    reviewLabel: 'Great',
    reviews: 2102,
    price: 189,
    stars: 4,
    type: 'Hotels',
    bedTypes: ['Double', 'Single'],
    address: 'Jl. Pratama, Nusa Dua, Bali',
  },
  {
    id: 'mandala-sky',
    name: 'Mandala Sky Luxury Villas',
    city: 'Bali',
    neighborhood: 'Uluwatu',
    locationLabel: 'Uluwatu, Bali • Cliff-top view',
    img: '/images/search-result/uluwatu-luxury-villa.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Breakfast', 'Spa', 'Private Beach'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Spa', 'Pet Friendly'],
    note: 'Cliff-edge infinity pool',
    reviewScore: 9.5,
    reviewLabel: 'Exceptional',
    reviews: 432,
    price: 480,
    was: 1200,
    stars: 5,
    type: 'Villas',
    bedTypes: ['King'],
    topChoice: true,
    address: 'Jl. Pemutih, Uluwatu, Bali',
  },
  {
    id: 'emerald-jungle',
    name: 'Emerald Jungle Retreat',
    city: 'Bali',
    neighborhood: 'Ubud',
    locationLabel: 'Ubud, Bali • Private Sanctuary',
    img: '/images/search-result/ubud-jungle-retreat.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Breakfast', 'Spa'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Spa'],
    note: 'Yoga and breakfast included',
    reviewScore: 9.1,
    reviewLabel: 'Exceptional',
    reviews: 671,
    price: 247,
    was: 450,
    stars: 4,
    type: 'Resorts',
    bedTypes: ['King', 'Double'],
    address: 'Jl. Kajeng, Ubud, Bali',
  },
  {
    id: 'seminyak-shores',
    name: 'Seminyak Shores Club',
    city: 'Bali',
    neighborhood: 'Seminyak',
    locationLabel: 'Seminyak, Bali • Beachfront Bliss',
    img: '/images/search-result/seminyak-beach-club-resort.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Breakfast', 'Gym'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Fitness Center', 'Parking'],
    note: 'Beach club access included',
    reviewScore: 8.7,
    reviewLabel: 'Excellent',
    reviews: 1188,
    price: 442,
    was: 680,
    stars: 5,
    type: 'Resorts',
    bedTypes: ['King'],
    address: 'Jl. Pantai Petitenget, Seminyak, Bali',
  },
  {
    id: 'kuta-coral',
    name: 'Kuta Coral Apartments',
    city: 'Bali',
    neighborhood: 'Patong',
    locationLabel: 'Patong • 5 min walk to beach',
    img: '/images/search-result/lumina-beach-villas.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Gym'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Fitness Center', 'Parking'],
    note: '4-night stay perks',
    reviewScore: 7.8,
    reviewLabel: 'Good',
    reviews: 564,
    price: 132,
    stars: 3,
    type: 'Apartments',
    bedTypes: ['Double', 'Single'],
    address: 'Jl. Pantai Kuta, Patong',
  },
  {
    id: 'karon-cove',
    name: 'Karon Cove Boutique',
    city: 'Phuket',
    neighborhood: 'Karon',
    locationLabel: 'Karon • Quiet beach lane',
    img: '/images/search-result/the-palms-sanctuary.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Breakfast'],
    facilities: ['Free Wi-Fi', 'Swimming Pool'],
    note: 'Adults-only sanctuary',
    reviewScore: 8.9,
    reviewLabel: 'Excellent',
    reviews: 312,
    price: 168,
    stars: 4,
    type: 'Hotels',
    bedTypes: ['King', 'Double'],
    address: 'Karon Beach Road, Phuket',
  },
  {
    id: 'kata-pearl',
    name: 'Kata Pearl Suites',
    city: 'Phuket',
    neighborhood: 'Kata',
    locationLabel: 'Kata • Sunset views',
    img: '/images/search-result/the-azure-serenity-resort.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Spa', 'Gym'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Spa', 'Fitness Center'],
    note: 'Free welcome cocktail',
    reviewScore: 9.3,
    reviewLabel: 'Exceptional',
    reviews: 902,
    price: 226,
    was: 290,
    stars: 5,
    type: 'Resorts',
    bedTypes: ['King'],
    topChoice: true,
    address: 'Kata Beach Road, Phuket',
  },
  {
    id: 'kamala-bay',
    name: 'Kamala Bay Residence',
    city: 'Phuket',
    neighborhood: 'Kamala',
    locationLabel: 'Kamala • Private balcony',
    img: '/images/search-result/uluwatu-luxury-villa.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Breakfast', 'Airport Shuttle'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Parking'],
    note: 'Self check-in available',
    reviewScore: 8.0,
    reviewLabel: 'Great',
    reviews: 421,
    price: 144,
    stars: 4,
    type: 'Apartments',
    bedTypes: ['Double'],
    address: 'Kamala Bay Road, Phuket',
  },
  {
    id: 'patong-pulse',
    name: 'Patong Pulse Hotel',
    city: 'Phuket',
    neighborhood: 'Patong',
    locationLabel: 'Patong • Walking street nearby',
    img: '/images/search-result/seminyak-beach-club-resort.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Gym', 'Breakfast'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Fitness Center'],
    note: 'Rooftop bar nightly',
    reviewScore: 7.4,
    reviewLabel: 'Good',
    reviews: 1840,
    price: 98,
    stars: 3,
    type: 'Hotels',
    bedTypes: ['Double', 'Single'],
    address: 'Soi Bangla, Patong, Phuket',
  },
  {
    id: 'ubud-canopy',
    name: 'Ubud Canopy Lofts',
    city: 'Bali',
    neighborhood: 'Ubud',
    locationLabel: 'Ubud • Treetop loft',
    img: '/images/search-result/ubud-jungle-retreat.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Spa', 'Breakfast'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Spa', 'Pet Friendly'],
    note: 'Sunrise yoga deck',
    reviewScore: 9.0,
    reviewLabel: 'Exceptional',
    reviews: 533,
    price: 312,
    stars: 4,
    type: 'Villas',
    bedTypes: ['King'],
    address: 'Jl. Tirta Tawar, Ubud, Bali',
  },
  {
    id: 'seminyak-glow',
    name: 'Seminyak Glow Hotel',
    city: 'Bali',
    neighborhood: 'Seminyak',
    locationLabel: 'Seminyak • Walk to nightlife',
    img: '/images/search-result/lumina-beach-villas.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Gym'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Fitness Center', 'Parking'],
    note: 'Same-day check-in',
    reviewScore: 8.2,
    reviewLabel: 'Great',
    reviews: 974,
    price: 176,
    was: 220,
    stars: 4,
    type: 'Hotels',
    bedTypes: ['Double'],
    address: 'Jl. Camplung Tanduk, Seminyak, Bali',
  },
  {
    id: 'uluwatu-edge',
    name: 'Uluwatu Edge Residences',
    city: 'Bali',
    neighborhood: 'Uluwatu',
    locationLabel: 'Uluwatu • Surf break view',
    img: '/images/search-result/the-palms-sanctuary.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Breakfast', 'Spa'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Spa'],
    note: 'Surf lessons on request',
    reviewScore: 8.8,
    reviewLabel: 'Excellent',
    reviews: 256,
    price: 358,
    stars: 5,
    type: 'Apartments',
    bedTypes: ['King'],
    address: 'Jl. Labuansait, Uluwatu, Bali',
  },
  {
    id: 'kata-breeze',
    name: 'Kata Breeze Inn',
    city: 'Phuket',
    neighborhood: 'Kata',
    locationLabel: 'Kata • Family friendly',
    img: '/images/search-result/the-azure-serenity-resort.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Breakfast'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Pet Friendly'],
    note: 'Kids stay free',
    reviewScore: 7.9,
    reviewLabel: 'Good',
    reviews: 388,
    price: 84,
    stars: 3,
    type: 'Hotels',
    bedTypes: ['Double', 'Single'],
    address: 'Kata Noi Road, Phuket',
  },
  {
    id: 'karon-amber',
    name: 'Karon Amber Suites',
    city: 'Phuket',
    neighborhood: 'Karon',
    locationLabel: 'Karon • Spa specialists',
    img: '/images/search-result/uluwatu-luxury-villa.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Spa', 'Gym'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Spa', 'Fitness Center'],
    note: 'Wellness package included',
    reviewScore: 9.4,
    reviewLabel: 'Exceptional',
    reviews: 612,
    price: 296,
    was: 360,
    stars: 5,
    type: 'Resorts',
    bedTypes: ['King'],
    topChoice: true,
    address: 'Karon Beach Road, Phuket',
  },
  {
    id: 'kamala-coral',
    name: 'Kamala Coral Hotel',
    city: 'Phuket',
    neighborhood: 'Kamala',
    locationLabel: 'Kamala • Modern rooms',
    img: '/images/search-result/seminyak-beach-club-resort.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Breakfast', 'Gym'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Fitness Center'],
    note: 'Rooftop sundeck',
    reviewScore: 8.5,
    reviewLabel: 'Excellent',
    reviews: 712,
    price: 158,
    stars: 4,
    type: 'Hotels',
    bedTypes: ['Double'],
    address: 'Kamala Beach Road, Phuket',
  },
  {
    id: 'nusa-pearl',
    name: 'Nusa Pearl Beach Resort',
    city: 'Bali',
    neighborhood: 'Nusa Dua',
    locationLabel: 'Nusa Dua • Adult retreat',
    img: '/images/search-result/the-azure-serenity-resort.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Spa', 'Gym', 'Private Beach'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Fitness Center', 'Spa'],
    note: 'Couples special promo',
    reviewScore: 9.0,
    reviewLabel: 'Exceptional',
    reviews: 1322,
    price: 268,
    was: 340,
    stars: 5,
    type: 'Resorts',
    bedTypes: ['King'],
    address: 'Pantai Mengiat, Nusa Dua, Bali',
  },
  {
    id: 'patong-skyline',
    name: 'Patong Skyline Apartments',
    city: 'Phuket',
    neighborhood: 'Patong',
    locationLabel: 'Patong • Skyline views',
    img: '/images/search-result/lumina-beach-villas.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Gym'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Fitness Center', 'Parking'],
    note: 'Co-working lounge',
    reviewScore: 8.1,
    reviewLabel: 'Great',
    reviews: 478,
    price: 119,
    stars: 4,
    type: 'Apartments',
    bedTypes: ['Double', 'Single'],
    address: 'Patong Beach Road, Phuket',
  },
  {
    id: 'ubud-orchid',
    name: 'Ubud Orchid Hideaway',
    city: 'Bali',
    neighborhood: 'Ubud',
    locationLabel: 'Ubud • Garden cottages',
    img: '/images/search-result/ubud-jungle-retreat.png',
    amenities: ['Free Wi-Fi', 'Pool', 'Spa', 'Breakfast'],
    facilities: ['Free Wi-Fi', 'Swimming Pool', 'Spa'],
    note: 'Daily yoga + meditation',
    reviewScore: 9.6,
    reviewLabel: 'Exceptional',
    reviews: 244,
    price: 392,
    stars: 5,
    type: 'Villas',
    bedTypes: ['King'],
    topChoice: true,
    address: 'Jl. Bisma, Ubud, Bali',
  },
];

export function findHotel(id?: string | null) {
  if (!id) return MOCK_HOTELS[0];
  return MOCK_HOTELS.find((h) => h.id === id) ?? MOCK_HOTELS[0];
}
