import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, basename, relative } from 'node:path';

const ROOT = process.cwd();
const ICONS_DIR = join(ROOT, 'public', 'icons');
const OUT = join(ROOT, 'src', 'lib', 'icons.generated.tsx');

function walk(dir, files = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, files);
    else if (entry.endsWith('.svg')) files.push(full);
  }
  return files;
}

function svgToJsx(raw) {
  let s = raw.replace(/<\?xml[\s\S]*?\?>/, '').trim();
  s = s.replace(/<!--[\s\S]*?-->/g, '');
  s = s.replace(/\sclass="([^"]*)"/g, ' className="$1"');
  s = s.replace(/\b(stroke|fill|stop)-([a-z]+)=/g, (m, p, q) => {
    const camel = p + q.charAt(0).toUpperCase() + q.slice(1);
    return ' ' + camel + '=';
  });
  s = s.replace(/\b(stop|flood|lighting)-color=/g, (m, p) => ' ' + p + 'Color=');
  s = s.replace(/\bclip-path=/g, ' clipPath=');
  s = s.replace(/\bclip-rule=/g, ' clipRule=');
  s = s.replace(/\bfill-rule=/g, ' fillRule=');
  s = s.replace(/\bstroke-width=/g, ' strokeWidth=');
  s = s.replace(/\bstroke-linecap=/g, ' strokeLinecap=');
  s = s.replace(/\bstroke-linejoin=/g, ' strokeLinejoin=');
  s = s.replace(/\bstroke-miterlimit=/g, ' strokeMiterlimit=');
  s = s.replace(/\bstroke-dasharray=/g, ' strokeDasharray=');
  s = s.replace(/\bstroke-dashoffset=/g, ' strokeDashoffset=');
  s = s.replace(/\btext-anchor=/g, ' textAnchor=');
  s = s.replace(/\bfont-family=/g, ' fontFamily=');
  s = s.replace(/\bfont-size=/g, ' fontSize=');
  s = s.replace(/\bfont-weight=/g, ' fontWeight=');
  s = s.replace(/\bxlink:href=/g, ' xlinkHref=');
  s = s.replace(/\bxmlns:xlink=/g, ' xmlnsXlink=');
  s = s.replace(/<svg([^>]*)>/, (m, attrs) => `<svg${attrs} {...props}>`);
  return s;
}

const files = walk(ICONS_DIR);
const entries = [];
for (const file of files) {
  const rel = relative(ICONS_DIR, file).replace(/\\/g, '/').replace(/\.svg$/, '');
  const raw = readFileSync(file, 'utf8');
  const jsx = svgToJsx(raw);
  entries.push({ key: rel, jsx });
}

mkdirSync(join(ROOT, 'src', 'lib'), { recursive: true });

const out = [
  "// AUTO-GENERATED by scripts/generate-icons.mjs",
  "// Do not edit by hand. Re-run: node scripts/generate-icons.mjs",
  "import type { ReactNode, SVGProps } from 'react';",
  "",
  "export type IconName =",
  ...entries.map((e, i) => `  | '${e.key}'${i === entries.length - 1 ? ';' : ''}`),
  "",
  "export const ICONS: Record<IconName, (props: SVGProps<SVGSVGElement>) => ReactNode> = {",
  ...entries.map((e) => `  '${e.key}': (props) => (${e.jsx}),`),
  "};",
  "",
].join('\n');

writeFileSync(OUT, out, 'utf8');
console.log(`Generated ${entries.length} icons → ${OUT}`);
